-- CreateTable
CREATE TABLE "Deal" (
    "id" SERIAL NOT NULL,
    "inStock" BOOLEAN NOT NULL,
    "colour" TEXT NOT NULL,
    "Telcos:month_cost" DOUBLE PRECISION NOT NULL,
    "Telcos:initial_cost" DOUBLE PRECISION NOT NULL,
    "Telcos:term" INTEGER NOT NULL,
    "Telcos:connectivity" TEXT NOT NULL,
    "Telcos:storage_size" TEXT NOT NULL,
    "Telcos:network" TEXT NOT NULL,
    "Telcos:inc_data" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "brand_name" TEXT NOT NULL,
    "incTexts" TEXT NOT NULL,
    "incMinutes" TEXT NOT NULL,
    "model_number" TEXT NOT NULL,
    "promotional_text" TEXT NOT NULL,
    "basket_link" TEXT NOT NULL,
    "merchant_image_url" TEXT NOT NULL,
    "merchant_name" TEXT NOT NULL,
    "aw_deep_link" TEXT NOT NULL,
    "product_name" TEXT NOT NULL,
    "aw_product_id" INTEGER NOT NULL,
    "merchant_product_id" INTEGER NOT NULL,
    "search_price" DOUBLE PRECISION NOT NULL,
    "merchant_category" TEXT NOT NULL,
    "store_price" DOUBLE PRECISION NOT NULL,
    "merchant_deep_link" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "last_updated" TIMESTAMP(3) NOT NULL,
    "display_price" TEXT NOT NULL,
    "data_feed_id" INTEGER NOT NULL,
    "brand_id" INTEGER NOT NULL,
    "aw_image_url" TEXT NOT NULL,
    "currency" TEXT NOT NULL,
    "is_for_sale" BOOLEAN NOT NULL,
    "merchant_thumb_url" TEXT NOT NULL,
    "large_image" TEXT NOT NULL,
    "alternate_image" TEXT NOT NULL,
    "reviews" TEXT NOT NULL,
    "averageRating" TEXT NOT NULL,
    "rating" TEXT NOT NULL,
    "upc" INTEGER NOT NULL,
    "parent_product_id" INTEGER NOT NULL,
    "product_GTIN" TEXT NOT NULL,
    "condition" TEXT NOT NULL,
    "base_price" DOUBLE PRECISION NOT NULL,
    "base_price_amount" DOUBLE PRECISION NOT NULL,
    "base_price_text" TEXT NOT NULL,
    "Telcos:subscription_name" TEXT NOT NULL,
    "Telcos:subscription_price_effective" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "Deal_pkey" PRIMARY KEY ("id")
);
