/*
  Warnings:

  - You are about to drop the `Deals` table. If the table is not empty, all the data it contains will be lost.

*/
-- AlterTable
ALTER TABLE "Phone" ADD COLUMN     "badge" TEXT;

-- DropTable
DROP TABLE "Deals";

-- CreateTable
CREATE TABLE "Deal" (
    "id" SERIAL NOT NULL,
    "aw_deep_link" TEXT,
    "product_name" TEXT,
    "aw_product_id" TEXT,
    "merchant_product_id" TEXT,
    "merchant_image_url" TEXT,
    "description" TEXT,
    "merchant_category" TEXT,
    "search_price" DOUBLE PRECISION NOT NULL,
    "merchant_name" TEXT,
    "merchant_id" TEXT,
    "category_name" TEXT,
    "category_id" TEXT,
    "aw_image_url" TEXT,
    "currency" TEXT,
    "store_price" DOUBLE PRECISION,
    "delivery_cost" TEXT,
    "merchant_deep_link" TEXT,
    "language" TEXT,
    "last_updated" TEXT,
    "display_price" TEXT,
    "data_feed_id" TEXT,
    "brand_name" TEXT,
    "brand_id" TEXT,
    "colour" TEXT,
    "product_short_description" TEXT,
    "specifications" TEXT,
    "condition" TEXT,
    "product_model" TEXT,
    "model_number" TEXT,
    "dimensions" TEXT,
    "keywords" TEXT,
    "promotional_text" TEXT,
    "product_type" TEXT,
    "commission_group" TEXT,
    "merchant_product_category_path" TEXT,
    "merchant_product_second_category" TEXT,
    "merchant_product_third_category" TEXT,
    "rrp_price" TEXT,
    "saving" TEXT,
    "savings_percent" TEXT,
    "base_price" DOUBLE PRECISION,
    "base_price_amount" DOUBLE PRECISION,
    "base_price_text" TEXT,
    "product_price_old" TEXT,
    "delivery_restrictions" TEXT,
    "delivery_weight" TEXT,
    "warranty" TEXT,
    "terms_of_contract" TEXT,
    "delivery_time" TEXT,
    "in_stock" INTEGER,
    "stock_quantity" TEXT,
    "valid_from" TEXT,
    "valid_to" TEXT,
    "is_for_sale" INTEGER,
    "web_offer" INTEGER,
    "pre_order" INTEGER,
    "stock_status" TEXT,
    "size_stock_status" TEXT,
    "size_stock_amount" TEXT,
    "merchant_thumb_url" TEXT,
    "large_image" TEXT,
    "alternate_image" TEXT,
    "aw_thumb_url" TEXT,
    "alternate_image_two" TEXT,
    "alternate_image_three" TEXT,
    "alternate_image_four" TEXT,
    "reviews" TEXT,
    "average_rating" TEXT,
    "rating" TEXT,
    "number_available" TEXT,
    "custom_1" TEXT,
    "custom_2" TEXT,
    "custom_3" TEXT,
    "custom_4" TEXT,
    "custom_5" TEXT,
    "custom_6" TEXT,
    "custom_7" TEXT,
    "custom_8" TEXT,
    "custom_9" TEXT,
    "ean" TEXT,
    "isbn" TEXT,
    "upc" TEXT,
    "mpn" TEXT,
    "parent_product_id" TEXT,
    "product_GTIN" TEXT,
    "basket_link" TEXT,
    "Telcos:contract_type" TEXT,
    "Telcos:term" TEXT,
    "Telcos:initial_cost" TEXT,
    "Telcos:month_cost" TEXT,
    "Telcos:gift" TEXT,
    "Telcos:inc_minutes" TEXT,
    "Telcos:inc_data" TEXT,
    "Telcos:connectivity" TEXT,
    "Telcos:inc_texts" TEXT,
    "Telcos:tariff" TEXT,
    "Telcos:storage_size" TEXT,
    "Telcos:special_offer" TEXT,
    "Telcos:network" TEXT,
    "Telcos:operating_system" TEXT,
    "Telcos:device_product_json" TEXT,
    "Telcos:device_product_version_json" TEXT,
    "Telcos:device_product_edition_json" TEXT,
    "Telcos:device_full_name" TEXT,
    "Telcos:device_description" TEXT,
    "Telcos:device_images_json" TEXT,
    "Telcos:device_features_json" TEXT,
    "Telcos:device_specifications_json" TEXT,
    "Telcos:network_details_json" TEXT,
    "Telcos:tariff_group_details_json" TEXT,
    "Telcos:tariff_details_json" TEXT,
    "Telcos:tariff_allowances_json" TEXT,
    "Telcos:tariff_out_of_plan_charges_json" TEXT,
    "Telcos:deal_tags_json" TEXT,
    "Telcos:deal_type_json" TEXT,
    "Telcos:deal_promo_info" TEXT,
    "Telcos:deal_extras_json" TEXT,
    "Telcos:deal_retailer_json" TEXT,
    "Telcos:deal_cost_json" TEXT,
    "Telcos:deal_discounts_json" TEXT,
    "Telcos:deal_cashback_json" TEXT,
    "Telcos:deal_legal_info" TEXT,
    "Telcos:subscription_name" TEXT,
    "Telcos:subscription_price_effective" DOUBLE PRECISION,
    "Telcos:subscription_renewal" TEXT,

    CONSTRAINT "Deal_pkey" PRIMARY KEY ("id")
);
